README修正(masa)
daikishirakawa/tenkue-app pull request #21
Opened 2021-01-20 01:21 UTC by masahiroz5

READMEの修正

2021-01-20 02:15 UTC, zidane-enlir requested changes

2021-01-20 02:15 UTC, zidane-enlir commented on README.md
> +
ここで、package-lock.json(及びpackage.json)に
書かれているnode_modulesをインストールしないと
次のnpm run startは動作しないと思うので追記が必要だと思います。

2021-01-20 03:22 UTC, zidane-enlir requested changes
修正提案をコメントしています。
お手隙の際にご覧ください。

2021-01-20 03:22 UTC, zidane-enlir commented on README.md
> +## 環境/技術
スラッシュの前に、環境依存文字みたいなのが入ってしまい、
「?」と出力されています。

2021-01-20 03:22 UTC, zidane-enlir commented on README.md
> +# README（共同開発）
READMEであることは、ファイル名で明確なので、
普通はアプリ名などを記載することが多いと思います。

2021-01-20 03:22 UTC, zidane-enlir commented on README.md
> + 1. `git clone (https://github.com/daikishirakawa/tenkue-app.git)`
git cloneコマンドの第一引数には、
brackets(小括弧)を抜かないと正常に動作しないと思います。

2021-01-20 14:35 UTC, zidane-enlir approved these changes

2021-01-20 14:37 UTC, zidane-enlir commented
@masahiroz5 

LGTM!!!

![LGTM](https://user-images.githubusercontent.com/40996175/105189606-7d38a700-5b78-11eb-9a82-937384e3a67b.png)

修正ありがとうございます。

2021-01-21 08:49 UTC, shoprogram commented
@masahiroz5 
お疲れさまです！
確認したいところが一点あります！
![image](https://user-images.githubusercontent.com/76730743/105326154-ca685780-5c10-11eb-9795-ef675e9e4bb4.png)

環境の横の文字は、仕様でしょうか？？

2021-01-21 09:57 UTC, masahiroz5 commented
@shoprogram 
vscode上のプレビューでは問題ないんですけどね。修正してみます。

2021-01-21 11:05 UTC, shoprogram commented
@masahiroz5 
修正確認しました！
LGTM！

2021-01-21 11:23 UTC, daikishirakawa commented
@masahiroz5 
LGTMです！

2021-01-21 13:08 UTC, merged